//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locamer2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class locamer_szEntities3 : DbContext
    {
        public locamer_szEntities3()
            : base("name=locamer_szEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Mobilhome> Mobilhomes { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Quantite> Quantites { get; set; }
        public virtual DbSet<Sejour> Sejours { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tarif> Tarifs { get; set; }
        public virtual DbSet<Typesejour> Typesejours { get; set; }
    }
}
