//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locamer2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quantite
    {
        public int id_quantite { get; set; }
        public int id_sejour { get; set; }
        public int id_option { get; set; }
        public int quantite1 { get; set; }
        public int nb_jour_location { get; set; }
    }
}
